# Generated by Django 4.0.6 on 2022-07-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('florihell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('observacoes', models.CharField(max_length=300)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florihell.produto')),
            ],
        ),
    ]
