# Generated by Django 4.0.6 on 2022-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florihell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
