# Generated by Django 4.0.6 on 2022-07-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florihell', '0002_produto_valor_produto_descricao_produto_nome_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
